# Milestone 3

Nama  : Nadia Syailendra
Batch : CODA-016-RMT

Program ini dibuat untuk melakukan tahap pra automasi yaitu melakukan eksplorasi data dengan Pandas dan validasi data menggunakan GX.

## Pre-Automation

## Import Library

In [1]:
import pandas as pd

## Load CSV to Pandas DataFrame

In [ ]:
df = pd.read_csv('data_raw.csv', delimiter=',')

## Data Exploration

In [3]:
#Menampilkan 5 data teratas
df.head(5)

,Customer_ID,Customer_Name,Gender,Age,State,City,Bank_Branch,Account_Type,Transaction_ID,Transaction_Date,...,Merchant_Category,Account_Balance,Transaction_Device,Transaction_Location,Device_Type,Is_Fraud,Transaction_Currency,Customer_Contact,Transaction_Description,Customer_Email
0,d5f6ec07-d69e-4f47-b9b4-7c58ff17c19e,Osha Tella,Male,60,Kerala,Thiruvananthapuram,Thiruvananthapuram Branch,Savings,4fa3208f-9e23-42dc-b330-844829d0c12c,23-01-2025,...,Restaurant,74557.27,Voice Assistant,"Thiruvananthapuram, Kerala",POS,0,INR,+9198579XXXXXX,Bitcoin transaction,oshaXXXXX@XXXXX.com
1,7c14ad51-781a-4db9-b7bd-67439c175262,Hredhaan Khosla,Female,51,Maharashtra,Nashik,Nashik Branch,Business,c9de0c06-2c4c-40a9-97ed-3c7b8f97c79c,11-01-2025,...,Restaurant,74622.66,POS Mobile Device,"Nashik, Maharashtra",Desktop,0,INR,+9191074XXXXXX,Grocery delivery,hredhaanXXXX@XXXXXX.com
2,3a73a0e5-d4da-45aa-85f3-528413900a35,Ekani Nazareth,Male,20,Bihar,Bhagalpur,Bhagalpur Branch,Savings,e41c55f9-c016-4ff3-872b-cae72467c75c,25-01-2025,...,Groceries,66817.99,ATM,"Bhagalpur, Bihar",Desktop,0,INR,+9197745XXXXXX,Mutual fund investment,ekaniXXX@XXXXXX.com
3,7902f4ef-9050-4a79-857d-9c2ea3181940,Yamini Ramachandran,Female,57,Tamil Nadu,Chennai,Chennai Branch,Business,7f7ee11b-ff2c-45a3-802a-49bc47c02ecb,19-01-2025,...,Entertainment,58177.08,POS Mobile App,"Chennai, Tamil Nadu",Mobile,0,INR,+9195889XXXXXX,Food delivery,yaminiXXXXX@XXXXXXX.com
4,3a4bba70-d9a9-4c5f-8b92-1735fd8c19e9,Kritika Rege,Female,43,Punjab,Amritsar,Amritsar Branch,Savings,f8e6ac6f-81a1-4985-bf12-f60967d852ef,30-01-2025,...,Entertainment,16108.56,Virtual Card,"Amritsar, Punjab",Mobile,0,INR,+9195316XXXXXX,Debt repayment,kritikaXXXX@XXXXXX.com

In [4]:
#Menampilkan summary DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 24 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Customer_ID              200000 non-null  object
 1   Customer_Name            200000 non-null  object
 2   Gender                   200000 non-null  object
 3   Age                      200000 non-null  int64
 4   State                    200000 non-null  object
 5   City                     200000 non-null  object
 6   Bank_Branch              200000 non-null  object
 7   Account_Type             200000 non-null  object
 8   Transaction_ID           200000 non-null  object
 9   Transaction_Date         200000 non-null  object
 10  Transaction_Time         200000 non-null  object
 11  Transaction_Amount       200000 non-null  float64
 12  Merchant_ID              200000 non-null  object
 13  Transaction_Type         200000 non-null  object
 14  Merchant_Category        200000 non-null  object
 15  Account_Balance          200000 non-null  float64
 16  Transaction_Device       200000 non-null  object
 17  Transaction_Location     200000 non-null  object
 18  Device_Type              200000 non-null  object
 19  Is_Fraud                 200000 non-null  int64
 20  Transaction_Currency     200000 non-null  object
 21  Customer_Contact         200000 non-null  object
 22  Transaction_Description  200000 non-null  object
 23  Customer_Email           200000 non-null  object
dtypes: float64(2), int64(2), object(20)
memory usage: 36.6+ MB

In [5]:
#Menampilkan deskripsi DataFrame
df.describe()

                 Age  Transaction_Amount  Account_Balance       Is_Fraud
count  200000.000000       200000.000000    200000.000000  200000.000000
mean       44.015110        49538.015554     52437.988784       0.050440
std        15.288774        28551.874004     27399.507128       0.218852
min        18.000000           10.290000      5000.820000       0.000000
25%        31.000000        24851.345000     28742.395000       0.000000
50%        44.000000        49502.440000     52372.555000       0.000000
75%        57.000000        74314.625000     76147.670000       0.000000
max        70.000000        98999.980000     99999.950000       1.000000

In [11]:
#Menampilkan tipe data di DataFrame
df.dtypes

Customer_ID                        object
Customer_Name                      object
Gender                             object
Age                                 int64
State                              object
City                               object
Bank_Branch                        object
Account_Type                       object
Transaction_ID                     object
Transaction_Date           datetime64[ns]
Transaction_Time           datetime64[ns]
Transaction_Amount                float64
Merchant_ID                        object
Transaction_Type                   object
Merchant_Category                  object
Account_Balance                   float64
Transaction_Device                 object
Transaction_Location               object
Device_Type                        object
Is_Fraud                            int64
Transaction_Currency               object
Customer_Contact                   object
Transaction_Description            object
Customer_Email                     object
dtype: object

### Check Missing Values

In [ ]:
#Checking if there is any missing values
df.isnull().sum() #No missing values found

Customer_ID                0
Customer_Name              0
Gender                     0
Age                        0
State                      0
City                       0
Bank_Branch                0
Account_Type               0
Transaction_ID             0
Transaction_Date           0
Transaction_Time           0
Transaction_Amount         0
Merchant_ID                0
Transaction_Type           0
Merchant_Category          0
Account_Balance            0
Transaction_Device         0
Transaction_Location       0
Device_Type                0
Is_Fraud                   0
Transaction_Currency       0
Customer_Contact           0
Transaction_Description    0
Customer_Email             0
dtype: int64

### Check Data Duplicates

In [8]:
#Checking data duplicates
df.duplicated().sum() #No data duplicates found

0

### Change Data Types

In [10]:
#Change data types to datetime for 'Transaction_Date' and 'Transaction_Time'
df['Transaction_Date'] = pd.to_datetime(df['Transaction_Date'])
df['Transaction_Time'] = pd.to_datetime(df['Transaction_Time'],format='%H:%M:%S', dayfirst=True)

## Data Validation

### Create Data Context

In [2]:
from great_expectations.data_context import FileDataContext

context = FileDataContext.create(project_root_dir='./')

### Connect to Datasource

In [3]:
# Create Datasource
datasource_name = 'csv-data-P2M3'
#datasource = context.sources.add_pandas(datasource_name)
datasource = context.get_datasource(datasource_name) #For retry when already created datasource

# Create Data Asset
asset_name = 'P2M3'
path_to_data = 'P2M3_Nadia_Syailendra_data_raw.csv'
#asset = datasource.add_csv_asset(asset_name)
asset = datasource.get_asset(asset_name)  #For retry when already created asset name

# Build batch request
batch_request = asset.build_batch_request()

### Create Expectation Suite

In [4]:
# Creat an expectation suite
expectation_suite_name = 'expectation-P2M3-dataset'
#context.add_or_update_expectation_suite(expectation_suite_name)
context.get_expectation_suite(expectation_suite_name)  #For retry when already created expectation suite

# Create a validator using above expectation suite
validator = context.get_validator(
    batch_request = batch_request,
    expectation_suite_name = expectation_suite_name
)

# Check the validator
validator.head()

Calculating Metrics:   0%|          | 0/1 [00:00<?, ?it/s]

,Customer_ID,Customer_Name,Gender,Age,State,City,Bank_Branch,Account_Type,Transaction_ID,Transaction_Date,...,Merchant_Category,Account_Balance,Transaction_Device,Transaction_Location,Device_Type,Is_Fraud,Transaction_Currency,Customer_Contact,Transaction_Description,Customer_Email
0,d5f6ec07-d69e-4f47-b9b4-7c58ff17c19e,Osha Tella,Male,60,Kerala,Thiruvananthapuram,Thiruvananthapuram Branch,Savings,4fa3208f-9e23-42dc-b330-844829d0c12c,23-01-2025,...,Restaurant,74557.27,Voice Assistant,"Thiruvananthapuram, Kerala",POS,0,INR,+9198579XXXXXX,Bitcoin transaction,oshaXXXXX@XXXXX.com
1,7c14ad51-781a-4db9-b7bd-67439c175262,Hredhaan Khosla,Female,51,Maharashtra,Nashik,Nashik Branch,Business,c9de0c06-2c4c-40a9-97ed-3c7b8f97c79c,11-01-2025,...,Restaurant,74622.66,POS Mobile Device,"Nashik, Maharashtra",Desktop,0,INR,+9191074XXXXXX,Grocery delivery,hredhaanXXXX@XXXXXX.com
2,3a73a0e5-d4da-45aa-85f3-528413900a35,Ekani Nazareth,Male,20,Bihar,Bhagalpur,Bhagalpur Branch,Savings,e41c55f9-c016-4ff3-872b-cae72467c75c,25-01-2025,...,Groceries,66817.99,ATM,"Bhagalpur, Bihar",Desktop,0,INR,+9197745XXXXXX,Mutual fund investment,ekaniXXX@XXXXXX.com
3,7902f4ef-9050-4a79-857d-9c2ea3181940,Yamini Ramachandran,Female,57,Tamil Nadu,Chennai,Chennai Branch,Business,7f7ee11b-ff2c-45a3-802a-49bc47c02ecb,19-01-2025,...,Entertainment,58177.08,POS Mobile App,"Chennai, Tamil Nadu",Mobile,0,INR,+9195889XXXXXX,Food delivery,yaminiXXXXX@XXXXXXX.com
4,3a4bba70-d9a9-4c5f-8b92-1735fd8c19e9,Kritika Rege,Female,43,Punjab,Amritsar,Amritsar Branch,Savings,f8e6ac6f-81a1-4985-bf12-f60967d852ef,30-01-2025,...,Entertainment,16108.56,Virtual Card,"Amritsar, Punjab",Mobile,0,INR,+9195316XXXXXX,Debt repayment,kritikaXXXX@XXXXXX.com

### Expectations

In [15]:
# Expectation 1 : Column 'Transaction_ID' must be unique

validator.expect_column_values_to_be_unique('Transaction_ID')

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "element_count": 200000,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

In [16]:
# Expectation 2 : Column 'Age' must be between 18 and 100

validator.expect_column_values_to_be_between(
    column='Age', min_value=18, max_value=100
)

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "element_count": 200000,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

In [17]:
# Expectation 3 : Column 'Account_Type' must contain one of the following 3 things :
# Savings
# Business
# Checking

validator.expect_column_values_to_be_in_set('Account_Type', ['Savings', 'Business', 'Checking'])

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "element_count": 200000,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

In [18]:
# Expectation 4 : Column 'Transaction_Amount' must in form of float

validator.expect_column_values_to_be_in_type_list('Transaction_Amount', ['float'])

Calculating Metrics:   0%|          | 0/1 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "observed_value": "float64"
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

In [19]:
# Expectation 5: Column 'Transaction_Currency' must be 3 digit long.

validator.expect_column_value_lengths_to_equal(
    column='Transaction_Currency',
    value=3
)

Calculating Metrics:   0%|          | 0/9 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "element_count": 200000,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

In [20]:
# Expectation 6: Column 'Customer_Email' contains '@','.' and alphanumeric in between '@' and '.'

validator.expect_column_values_to_match_regex(
    column="Customer_Email",
    regex = r"^[^@\s]+@[^@\s]+\.+[^@\s]+$"
)

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "element_count": 200000,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

In [5]:
# Expectation 7: Column 'Customer_Name' must be between 2 to 40 characters

validator.expect_column_value_lengths_to_be_between(
    column='Customer_Name',
    min_value= 2,
    max_value= 40
)

Calculating Metrics:   0%|          | 0/9 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "element_count": 200000,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

### Save to Expectation Suite

In [22]:
#Menyimpan ke Expectation Suite
validator.save_expectation_suite(discard_failed_expectations=False)

### Create Checkpoint

In [23]:
checkpoint_1 = context.add_or_update_checkpoint(
    name = 'checkpoint_1',
    validator = validator,
)

In [24]:
# Run a checkpoint

checkpoint_result = checkpoint_1.run()

Calculating Metrics:   0%|          | 0/52 [00:00<?, ?it/s]

### Create Data Docs

In [25]:
# Build data docs

context.build_data_docs()

{'local_site': 'file://c:\\Users\\lenovo\\coda\\p2-coda016-rmt-m3-nadia-syailendra\\gx\\uncommitted/data_docs/local_site/index.html'}